package it.apexweather.domain

import kotlinx.serialization.Serializable
import java.util.Locale

/** The weather station that speaks for a place, precomputed by `tools/generate-places.py`. */
@Serializable
data class NearbyStation(
    val code: String,
    val name: String,
    val lat: Double,
    val lon: Double,
    val altitudeM: Int,
    val distanceKm: Double,
    /**
     * How steady village-minus-station is in ICON-D2 over eight weeks, in kelvin — the number this
     * station was chosen on, and a fair warning about how much the reading is worth.
     *
     * A station in the same air has a difference that barely moves whatever its size; one over a
     * ridge spends every clear night in a different inversion. Null where the place had only one
     * candidate, or the models could not be asked when the catalogue was generated.
     */
    val stabilityK: Double? = null,
    /**
     * The station's own skyline, in tenths of a degree per five degrees of bearing. See [Horizon].
     *
     * Its own, and not the village's, because a thermometer in this province is usually a long way
     * below the place that reads it — Dorf Tirol's stands 264 m down on the valley floor — and the
     * valley floor loses the sun earlier and gets it later than the slope above. [StationSun] reads
     * a pyranometer against what the sky *should* be delivering, and that question is asked at the
     * pyranometer.
     */
    val horizon: List<Int>? = null,
)

/**
 * One South Tyrolean municipality: everything that differs between locations, in one object.
 *
 * The ISTAT code is what SIAG KMOS is addressed by, the coordinates are what Open-Meteo and
 * GeoSphere are asked about, the district is which of the seven bulletins this place reads, and
 * the station is the nearest thermometer — null where none is close enough to speak for the place,
 * in which case the app shows the model consensus and says nothing about a measurement.
 */
@Serializable
data class Place(
    val istat: String,
    val nameDe: String,
    val nameIt: String,
    val nameEn: String,
    val lat: Double,
    val lon: Double,
    val altitudeM: Int,
    val district: Int,
    val station: NearbyStation? = null,
    /**
     * The mountains this place is surrounded by, as elevation angles: tenths of a degree, one every
     * five degrees of bearing clockwise from true north, generated by `tools/horizons.py`.
     *
     * Null in a catalogue written before this existed, and the app falls back to the flat horizon it
     * used to assume everywhere — see [Horizon.usable]. Measured rather than guessed: Dorf Tirol's
     * northern skyline is 19,4° of Texelgruppe and its western one 24,2°, against the 0° the
     * astronomical sunset silently assumes.
     */
    val horizon: List<Int>? = null,
) {
    /** The name in the reader's language, never in the JVM's default. */
    fun name(locale: Locale): String = when (locale.language) {
        "it" -> nameIt
        "en" -> nameEn
        else -> nameDe
    }
}
