package it.apexweather.domain

import kotlinx.serialization.Serializable
import java.util.Locale

/** The weather station that speaks for a place, precomputed by `tools/generate-places.py`. */
@Serializable
data class NearbyStation(
    val code: String,
    val name: String,
    val lat: Double,
    val lon: Double,
    val altitudeM: Int,
    val distanceKm: Double,
    /**
     * Which network this thermometer belongs to: `"siag"` for the province's own, `"wu"` for a
     * Weather Underground contributor station.
     *
     * Not decoration. A provincial station is a screened instrument on a surveyed site with an
     * altitude somebody measured; an amateur one is a thermometer a neighbour put up, with an
     * altitude typed into a web form — six of the ten around Dorf Tirol claim a valley floor while
     * standing on a hillside, out by 210 to 416 m against the DEM. `tools/generate-places.py`
     * throws those out before they reach the catalogue, but the reader is still told which of the
     * two kinds is on their screen, and the share card refuses to redistribute the amateur one.
     *
     * Defaulted, so a catalogue written before this reads as the province's own, which it is.
     */
    val network: String = "siag",
    /**
     * How steady village-minus-station is in ICON-D2 over eight weeks, in kelvin — the number this
     * station was chosen on, and a fair warning about how much the reading is worth.
     *
     * A station in the same air has a difference that barely moves whatever its size; one over a
     * ridge spends every clear night in a different inversion. Null where the place had only one
     * candidate, or the models could not be asked when the catalogue was generated.
     */
    val stabilityK: Double? = null,
    /**
     * The station's own skyline, in tenths of a degree per five degrees of bearing. See [Horizon].
     *
     * Its own, and not the village's, because a thermometer in this province is usually a long way
     * below the place that reads it — Dorf Tirol's stands 264 m down on the valley floor — and the
     * valley floor loses the sun earlier and gets it later than the slope above. [StationSun] reads
     * a pyranometer against what the sky *should* be delivering, and that question is asked at the
     * pyranometer.
     */
    val horizon: List<Int>? = null,
)

/**
 * One South Tyrolean municipality: everything that differs between locations, in one object.
 *
 * The ISTAT code is what SIAG KMOS is addressed by, the coordinates are what Open-Meteo and
 * GeoSphere are asked about, the district is which of the seven bulletins this place reads, and
 * the station is the nearest thermometer — null where none is close enough to speak for the place,
 * in which case the app shows the model consensus and says nothing about a measurement.
 */
@Serializable
data class Place(
    val istat: String,
    val nameDe: String,
    val nameIt: String,
    val nameEn: String,
    val lat: Double,
    val lon: Double,
    val altitudeM: Int,
    val district: Int,
    val station: NearbyStation? = null,
    /**
     * An amateur station that speaks for this place better than the province's own does.
     *
     * Present only where one exists, answered when the catalogue was generated, agreed with the DEM
     * about its own altitude, and then **beat the provincial station on the stability measure** —
     * eight weeks of ICON-D2, village-minus-station — that chose the provincial one in the first
     * place. Null for most of the 116, which keep the thermometer they have and should.
     *
     * It never replaces [station]. The provincial reading is still fetched, it is what the app
     * falls back to, and it supplies every quantity the amateur station does not publish. That
     * fallback is an ordinary hourly event rather than an error path: Weather Underground answers
     * "nothing in the last 60 minutes" for a perfectly live station, and does so intermittently.
     */
    val pws: NearbyStation? = null,
    /**
     * The mountains this place is surrounded by, as elevation angles: tenths of a degree, one every
     * five degrees of bearing clockwise from true north, generated by `tools/horizons.py`.
     *
     * Null in a catalogue written before this existed, and the app falls back to the flat horizon it
     * used to assume everywhere — see [Horizon.usable]. Measured rather than guessed: Dorf Tirol's
     * northern skyline is 19,4° of Texelgruppe and its western one 24,2°, against the 0° the
     * astronomical sunset silently assumes.
     */
    val horizon: List<Int>? = null,
) {
    /**
     * The thermometer this place actually reads: the amateur one where there is one, the province's
     * otherwise, and null where neither is close enough to speak for the place.
     *
     * Everything that asks "what does the station say" asks this. [station] alone remains the
     * fallback, and the source of the quantities an amateur station does not publish — ITIROL16, the
     * best-sited station in Dorf Tirol, has no pyranometer at all, and handing [StationSun] a null
     * where the provincial station has a real reading would switch it off for the place.
     */
    val readingStation: NearbyStation? get() = pws ?: station

    /**
     * This place as the reader's settings have it — without its amateur station where they have
     * switched amateur stations off.
     *
     * Applied at the edge, where settings and place meet, rather than inside
     * [it.apexweather.data.WeatherRepository]. The repository deliberately knows nothing about
     * settings, and the alternative — a flag threaded through `refresh`, `refreshObservation`, the
     * snapshot flow and `recordStationHour` — would be four places that have to agree about one
     * boolean. A place with no `pws` is a state the whole feature already handles correctly,
     * because it is the state 100-odd of the 116 are in, so removing it here needs nothing
     * downstream to change.
     */
    fun withAmateurStation(allowed: Boolean): Place =
        if (allowed || pws == null) this else copy(pws = null)

    /**
     * This place reading the station its reader picked, where they picked one.
     *
     * `"siag"` means they asked for the province's own here, which is exactly a place with no
     * `pws` — the state 48 of the 116 are in, so nothing downstream needs to learn about it.
     */
    fun withChosenStation(chosen: it.apexweather.data.ChosenStation?): Place = when {
        chosen == null || chosen.istat != istat -> this
        chosen.network == "siag" -> copy(pws = null)
        else -> copy(pws = chosen.toStation())
    }

    /**
     * This place as these settings have it — the policy, where [withAmateurStation] is the
     * mechanism.
     *
     * Two conditions, in one function, because three callers apply it: the app's place flow, the
     * hourly worker and the widget. A rule spelled out in three places is one that will eventually
     * be spelled out differently in one of them.
     *
     * The key half is not a convenience. [readingStation] is `pws ?: station`, and the Open-Meteo
     * *station reference* — the models' own view of the thermometer, which [StationDownscale]
     * subtracts from the village — is fetched at its coordinates. A place that kept its `pws` with
     * no key to fetch it would have the models asked about a point whose thermometer is never read,
     * while the hero fell back to the provincial reading, and the offset between them would be two
     * different places subtracted from each other.
     *
     * The reader's own choice is applied *first* and the two global conditions after it, because
     * both of those are statements about every amateur instrument — "I do not trust ones nobody
     * maintains" and "I have given no key" — and one place's preference does not answer either.
     */
    fun forSettings(settings: it.apexweather.data.AppSettings): Place =
        withChosenStation(settings.chosenStations.firstOrNull { it.istat == istat })
            .withAmateurStation(settings.amateurStations && !settings.wuApiKey.isNullOrBlank())

    /** The name in the reader's language, never in the JVM's default. */
    fun name(locale: Locale): String = when (locale.language) {
        "it" -> nameIt
        "en" -> nameEn
        else -> nameDe
    }
}
