package it.apexweather.domain

/**
 * RainViewer's "Universal Blue" colours, as ARGB, one per whole dBZ from [MIN_DBZ] upward.
 *
 * Generated by `tools/radar-colors.py` from RainViewer's published table. Do not edit by hand.
 */
internal object RadarColorTable {
    const val MIN_DBZ = -10

    val RAIN: IntArray = intArrayOf(
        0x14636159.toInt(), 0x1966635A.toInt(), 0x1E69665C.toInt(), 0x246C685D.toInt(),
        0x296F6B5F.toInt(), 0x2E726E61.toInt(), 0x34757062.toInt(), 0x39787364.toInt(),
        0x3E7C7565.toInt(), 0x447F7867.toInt(), 0x49827B69.toInt(), 0x4E857D6A.toInt(),
        0x5488806C.toInt(), 0x598B826D.toInt(), 0x5E8E856F.toInt(), 0x64928871.toInt(),
        0x6E9E9375.toInt(), 0x78AA9E79.toInt(), 0x82B6A97E.toInt(), 0x8CC2B482.toInt(),
        0x96CEC087.toInt(), 0xA0D2C48B.toInt(), 0xAAD6C88F.toInt(), 0xB4DACC93.toInt(),
        0xBEDED097.toInt(), 0xFF88DDEE.toInt(), 0xFF6CD1EB.toInt(), 0xFF51C5E8.toInt(),
        0xFF36BAE5.toInt(), 0xFF1BAEE2.toInt(), 0xFF00A3E0.toInt(), 0xFF009AD5.toInt(),
        0xFF0091CA.toInt(), 0xFF0088BF.toInt(), 0xFF007FB4.toInt(), 0xFF0077AA.toInt(),
        0xFF0070A3.toInt(), 0xFF00699C.toInt(), 0xFF006295.toInt(), 0xFF005B8E.toInt(),
        0xFF005588.toInt(), 0xFF005180.toInt(), 0xFF004E78.toInt(), 0xFF004A70.toInt(),
        0xFF004768.toInt(), 0xFFFFEE00.toInt(), 0xFFFFE000.toInt(), 0xFFFFD200.toInt(),
        0xFFFFC500.toInt(), 0xFFFFB700.toInt(), 0xFFFFAA00.toInt(), 0xFFFF9F00.toInt(),
        0xFFFF9500.toInt(), 0xFFFF8B00.toInt(), 0xFFFF8100.toInt(), 0xFFFF4400.toInt(),
        0xFFF23600.toInt(), 0xFFE62800.toInt(), 0xFFD91B00.toInt(), 0xFFCD0D00.toInt(),
        0xFFC10000.toInt(), 0xFFA80000.toInt(), 0xFF8F0000.toInt(), 0xFF760000.toInt(),
        0xFF5D0000.toInt(), 0xFFFFAAFF.toInt(), 0xFFFF9FFF.toInt(), 0xFFFF95FF.toInt(),
        0xFFFF8BFF.toInt(), 0xFFFF81FF.toInt(), 0xFFFF77FF.toInt(), 0xFFFF6CFF.toInt(),
        0xFFFF62FF.toInt(), 0xFFFF58FF.toInt(), 0xFFFF4EFF.toInt(), 0xFFFFFFFF.toInt(),
        0xFFFFFFFF.toInt(), 0xFFFFFFFF.toInt(), 0xFFFFFFFF.toInt(), 0xFFFFFFFF.toInt(),
        0xFFFFFFFF.toInt(), 0xFFFFFFFF.toInt(), 0xFFFFFFFF.toInt(), 0xFFFFFFFF.toInt(),
        0xFFFFFFFF.toInt(), 0xFF00FF00.toInt(), 0xFF00FF00.toInt(), 0xFF00FF00.toInt(),
        0xFF00FF00.toInt(), 0xFF00FF00.toInt(), 0xFF00FF00.toInt(), 0xFF00FF00.toInt(),
        0xFF00FF00.toInt(), 0xFF00FF00.toInt(), 0xFF00FF00.toInt(), 0xFF00FF00.toInt(),
        0xFF00FF00.toInt(), 0xFF00FF00.toInt(), 0xFF00FF00.toInt(), 0xFF00FF00.toInt(),
        0xFF00FF00.toInt(), 0xFF00FF00.toInt(), 0xFF00FF00.toInt(), 0xFF00FF00.toInt(),
        0xFF00FF00.toInt(), 0xFF00FF00.toInt(),
    )

    val SNOW: IntArray = intArrayOf(
        0x00CFFFFF.toInt(), 0x0CCEFFFF.toInt(), 0x19CDFFFF.toInt(), 0x26CCFFFF.toInt(),
        0x33CBFFFF.toInt(), 0x3FCBFFFF.toInt(), 0x4CCAFFFF.toInt(), 0x59C9FFFF.toInt(),
        0x66C8FFFF.toInt(), 0x72C7FFFF.toInt(), 0x7FC7FFFF.toInt(), 0x8CC6FFFF.toInt(),
        0x99C5FFFF.toInt(), 0xA5C4FFFF.toInt(), 0xB2C3FFFF.toInt(), 0xBFC3FFFF.toInt(),
        0xCCC2FFFF.toInt(), 0xD8C1FFFF.toInt(), 0xE5C0FFFF.toInt(), 0xF2BFFFFF.toInt(),
        0xFFBFFFFF.toInt(), 0xFFB8F8FF.toInt(), 0xFFB2F2FF.toInt(), 0xFFABEBFF.toInt(),
        0xFFA5E5FF.toInt(), 0xFF9FDFFF.toInt(), 0xFF98D8FF.toInt(), 0xFF92D2FF.toInt(),
        0xFF8BCBFF.toInt(), 0xFF85C5FF.toInt(), 0xFF7FBFFF.toInt(), 0xFF78B8FF.toInt(),
        0xFF72B2FF.toInt(), 0xFF6BABFF.toInt(), 0xFF65A5FF.toInt(), 0xFF5F9FFF.toInt(),
        0xFF5B9BFF.toInt(), 0xFF5898FF.toInt(), 0xFF5595FF.toInt(), 0xFF5292FF.toInt(),
        0xFF4F8FFF.toInt(), 0xFF4B8BFF.toInt(), 0xFF4888FF.toInt(), 0xFF4585FF.toInt(),
        0xFF4282FF.toInt(), 0xFF3F7FFF.toInt(), 0xFF3B7BFF.toInt(), 0xFF3878FF.toInt(),
        0xFF3575FF.toInt(), 0xFF3272FF.toInt(), 0xFF2F6FFF.toInt(), 0xFF2B6BFF.toInt(),
        0xFF2868FF.toInt(), 0xFF2565FF.toInt(), 0xFF2262FF.toInt(), 0xFF1F5FFF.toInt(),
        0xFF1B5BFF.toInt(), 0xFF1858FF.toInt(), 0xFF1555FF.toInt(), 0xFF1252FF.toInt(),
        0xFF0F4FFF.toInt(), 0xFF0C4BFF.toInt(), 0xFF0948FF.toInt(), 0xFF0645FF.toInt(),
        0xFF0242FF.toInt(), 0xFF003FFF.toInt(), 0xFF003BFF.toInt(), 0xFF0038FF.toInt(),
        0xFF0035FF.toInt(), 0xFF0032FF.toInt(), 0xFF002FFF.toInt(), 0xFF002BFF.toInt(),
        0xFF0028FF.toInt(), 0xFF0025FF.toInt(), 0xFF0022FF.toInt(), 0xFF001FFF.toInt(),
        0xFF001BFF.toInt(), 0xFF0018FF.toInt(), 0xFF0015FF.toInt(), 0xFF0012FF.toInt(),
        0xFF000FFF.toInt(), 0xFF000CFF.toInt(), 0xFF0009FF.toInt(), 0xFF0006FF.toInt(),
        0xFF0002FF.toInt(), 0xFF0000FF.toInt(), 0xFF0000FF.toInt(), 0xFF0000FF.toInt(),
        0xFF0000FF.toInt(), 0xFF0000FF.toInt(), 0xFF0000FF.toInt(), 0xFF0000FF.toInt(),
        0xFF0000FF.toInt(), 0xFF0000FF.toInt(), 0xFF0000FF.toInt(), 0xFF0000FF.toInt(),
        0xFF0000FF.toInt(), 0xFF0000FF.toInt(), 0xFF0000FF.toInt(), 0xFF0000FF.toInt(),
        0xFF0000FF.toInt(), 0xFF0000FF.toInt(), 0xFF0000FF.toInt(), 0xFF0000FF.toInt(),
        0xFF0000FF.toInt(), 0xFF0000FF.toInt(),
    )
}
