package it.apexweather.data

import android.content.Context
import dagger.hilt.android.qualifiers.ApplicationContext
import it.apexweather.domain.Place
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import kotlinx.serialization.builtins.ListSerializer
import kotlinx.serialization.json.Json
import java.text.Collator
import java.text.Normalizer
import java.util.Locale
import javax.inject.Inject
import javax.inject.Singleton

/**
 * The 116 municipalities of the province, read once from `assets/places.json`.
 *
 * Bundled rather than fetched: the picker has to work before the first refresh and without a
 * connection, and the list only changes when Italy redraws a municipal boundary — not often enough
 * to pay for a network call on every launch. Generated by `tools/generate-places.py`.
 */
@Singleton
class PlaceCatalogue @Inject constructor(
    @ApplicationContext private val context: Context,
) {
    private val json = Json { ignoreUnknownKeys = true }

    private val loaded: List<Place> by lazy {
        context.assets.open(ASSET).bufferedReader().use {
            json.decodeFromString(ListSerializer(Place.serializer()), it.readText())
        }
    }

    /** Parsing 37 kB is quick, but it is still file I/O, so it never happens on the main thread. */
    suspend fun all(): List<Place> = withContext(Dispatchers.IO) { loaded }

    suspend fun byIstat(istat: String): Place? = all().firstOrNull { it.istat == istat }

    /**
     * Matches any of the three names, ignoring case and diacritics, so "meran" finds both Meran and
     * Merano. An empty query is every place, in the reader's own alphabetical order.
     */
    suspend fun search(query: String, locale: Locale): List<Place> {
        // A Collator, not a fold: alphabetical order is the reader's language's business, and
        // German and Italian do not agree about where an accented letter belongs.
        val collator = Collator.getInstance(locale).apply { strength = Collator.PRIMARY }
        val places = all().sortedWith(compareBy(collator) { it.name(locale) })
        val needles = variants(query)
        if (needles.all { it.isEmpty() }) return places
        return places.filter { place ->
            listOf(place.nameDe, place.nameIt, place.nameEn).any { name ->
                variants(name).any { hay -> needles.any { hay.contains(it) } }
            }
        }
    }

    /**
     * Both ways a reader might type a name that carries an umlaut: Mölten as "molten", with the
     * diacritic simply dropped, and as "moelten", the way German writes it on a keyboard that has
     * no umlaut. Matching either against either means neither spelling is a dead end.
     */
    private fun variants(s: String): List<String> {
        val lower = s.trim().lowercase(Locale.ROOT)
        val expanded = lower.replace("ö", "oe").replace("ü", "ue").replace("ä", "ae").replace("ß", "ss")
        val stripped = Normalizer.normalize(lower, Normalizer.Form.NFD).replace(COMBINING_MARKS, "")
        return listOf(expanded, stripped).distinct()
    }

    private companion object {
        const val ASSET = "places.json"
        val COMBINING_MARKS = Regex("\\p{Mn}+")
    }
}
