package it.apexweather.data

import android.content.Context
import dagger.hilt.android.qualifiers.ApplicationContext
import it.apexweather.domain.Place
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import kotlinx.serialization.builtins.ListSerializer
import kotlinx.serialization.json.Json
import java.text.Collator
import java.text.Normalizer
import java.util.Locale
import javax.inject.Inject
import javax.inject.Singleton

/**
 * The 116 municipalities of the province, read once from `assets/places.json`.
 *
 * Bundled rather than fetched: the picker has to work before the first refresh and without a
 * connection, and the list only changes when Italy redraws a municipal boundary — not often enough
 * to pay for a network call on every launch. Generated by `tools/generate-places.py`.
 */
@Singleton
class PlaceCatalogue @Inject constructor(
    @ApplicationContext private val context: Context,
) {
    private val json = Json { ignoreUnknownKeys = true }

    private val loaded: List<Place> by lazy {
        context.assets.open(ASSET).bufferedReader().use {
            json.decodeFromString(ListSerializer(Place.serializer()), it.readText())
        }
    }

    /**
     * Every place's three names, already folded both ways a reader might type them.
     *
     * Built once with the catalogue rather than per query. Folding is a `Normalizer.normalize` and
     * a regex replace each, so doing it at search time was 116 places x 3 names x 2 forms of that
     * work for every keystroke, to fold the same 348 strings to the same 348 answers every time.
     * The names come out of a bundled asset and never change.
     */
    private val haystacks: Map<String, List<String>> by lazy {
        loaded.associate { place ->
            place.istat to listOf(place.nameDe, place.nameIt, place.nameEn).flatMap(::variants).distinct()
        }
    }

    /** The same list by ISTAT code, because [byIstat] is asked far more often than it is obvious. */
    private val byCode: Map<String, Place> by lazy { loaded.associateBy { it.istat } }

    /** Parsing 37 kB is quick, but it is still file I/O, so it never happens on the main thread. */
    suspend fun all(): List<Place> = withContext(Dispatchers.IO) { loaded }

    suspend fun byIstat(istat: String): Place? = withContext(Dispatchers.IO) { byCode[istat] }

    /**
     * Matches any of the three names, ignoring case and diacritics, so "meran" finds both Meran and
     * Merano. An empty query is every place, in the reader's own alphabetical order.
     *
     * The whole of it runs off the main thread, not only the asset read. The sort is a `Collator`
     * over 116 places and the filter walks their folded names; that is a keystroke's worth of work
     * on whatever thread the caller is on, and the caller is a ViewModel, whose scope is the main
     * one. Every other piece of per-emission work in this app is explicitly moved off it.
     */
    suspend fun search(query: String, locale: Locale): List<Place> {
        // Through `all`, so the very first search still reads the asset on the IO dispatcher rather
        // than dragging file I/O onto Default with the sort.
        val catalogue = all()
        return withContext(Dispatchers.Default) { matching(catalogue, query, locale) }
    }

    private fun matching(catalogue: List<Place>, query: String, locale: Locale): List<Place> {
        // A Collator, not a fold: alphabetical order is the reader's language's business, and
        // German and Italian do not agree about where an accented letter belongs.
        val collator = Collator.getInstance(locale).apply { strength = Collator.PRIMARY }
        val places = catalogue.sortedWith(compareBy(collator) { it.name(locale) })
        val needles = variants(query)
        if (needles.all { it.isEmpty() }) return places
        return places.filter { place ->
            haystacks[place.istat].orEmpty().any { hay -> needles.any { hay.contains(it) } }
        }
    }

    /**
     * Both ways a reader might type a name that carries an umlaut: Mölten as "molten", with the
     * diacritic simply dropped, and as "moelten", the way German writes it on a keyboard that has
     * no umlaut. Matching either against either means neither spelling is a dead end.
     */
    private fun variants(s: String): List<String> {
        val lower = s.trim().lowercase(Locale.ROOT)
        val expanded = lower.replace("ö", "oe").replace("ü", "ue").replace("ä", "ae").replace("ß", "ss")
        val stripped = Normalizer.normalize(lower, Normalizer.Form.NFD).replace(COMBINING_MARKS, "")
        return listOf(expanded, stripped).distinct()
    }

    private companion object {
        const val ASSET = "places.json"
        val COMBINING_MARKS = Regex("\\p{Mn}+")
    }
}
