#!/usr/bin/env python3
"""Writes RadarColorTable.kt from RainViewer's published colour table.

RainViewer publishes the RGBA of every colour scheme at every whole dBZ
(https://www.rainviewer.com/files/rainviewer_api_colors_table.csv), in two blocks: rain, then snow.
The tiles this app receives are the "Universal Blue" column. Run from the repository root and
review the diff: a change here changes how every radar pixel is read.
"""
import csv
import pathlib
import sys

SRC = pathlib.Path("app/src/test/resources/fixtures/map-2026-09-14/rainviewer_api_colors_table.csv")
OUT = pathlib.Path("app/src/main/kotlin/it/apexweather/domain/RadarColorTable.kt")
COLUMN = "Universal Blue"
MIN_DBZ = -10


def main() -> None:
    rows = list(csv.reader(SRC.read_text().splitlines()))
    col = rows[0].index(COLUMN)
    blocks: list[dict[int, int]] = []
    for row in rows[1:]:
        if row[0] == "-32":
            blocks.append({})
        rgba = int(row[col].strip().lstrip("#"), 16)
        blocks[-1][int(row[0])] = ((rgba & 0xFF) << 24) | (rgba >> 8)
    if len(blocks) != 2:
        sys.exit(f"expected a rain and a snow block, found {len(blocks)}")

    def body(block: dict[int, int]) -> str:
        values = [block[d] for d in range(MIN_DBZ, max(block) + 1)]
        lines = [", ".join(f"0x{v:08X}.toInt()" for v in values[i:i + 4]) for i in range(0, len(values), 4)]
        return ",\n        ".join(lines)

    OUT.write_text(f"""package it.apexweather.domain

/**
 * RainViewer's "{COLUMN}" colours, as ARGB, one per whole dBZ from [MIN_DBZ] upward.
 *
 * Generated by `tools/radar-colors.py` from RainViewer's published table. Do not edit by hand.
 */
internal object RadarColorTable {{
    const val MIN_DBZ = {MIN_DBZ}

    val RAIN: IntArray = intArrayOf(
        {body(blocks[0])},
    )

    val SNOW: IntArray = intArrayOf(
        {body(blocks[1])},
    )
}}
""")
    print(f"wrote {OUT}: rain {max(blocks[0]) - MIN_DBZ + 1}, snow {max(blocks[1]) - MIN_DBZ + 1} entries")


if __name__ == "__main__":
    main()
